### ISSUE TITLE
Вопрос по коду

### ISSUE THREAD

**Issue by razor28** [trifonov-ivan/swift2-json#1]
Не могли бы вы пояснить как работает функция из Playground2:

```
func decode<T: Deserializeable>(forKey key: String) throws -> T {
  return try appendPathComponentToError(T.decode(self.resultForKey(key)), component: key)
}
```

Никак не пойму откуда берется generic переменная  Т в теле функции ведь она не передается как параметр. Не нашел примеров в интернете с подобным кодом.
Заранее спасибо.

**Comment by trifonov-ivan** [comment]
Посмотрите на протокол Deserializeable

```
protocol Deserializeable {
    static func decode(input: AnyObject) throws -> Self
}
```

decode - это static функция типа - то есть в данном случае T - это не переменная - а всего-лишь название типа.

То есть если мы делаем

```
let a: SomeJSONDecodable = decoder.decode(forKey: "anyKey")
```

то T становится SomeJSONDecodable и вызов превращается во вполне валидный

```
SomeJSONDecodable.decode(self.resultForKey(key))
```

**Comment by razor28** [comment]
Теперь все встало на свои места. Спасибо большое!
